#vol-0712acc6ef0d75b50
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-immediate
  awsElasticBlockStore:
    volumeID: vol-0712acc6ef0d75b50    # Replace with your EBS volume ID
    fsType: ext4

