apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: jenkins
spec:
  volumes:
    - name: test-vol
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: test-vol
          mountPath: /data

